import {ingredients,recipes,customers,SAVE_KEY,fresh,total,needFor,action,encode,decode} from './day1-core.mjs';
const $=document.querySelector('#app');
const imageBase='../assets/characters/named/be_ti/candidates/alternate_model_v1/';
const beti=imageBase+'queue_wait_normal_pilot/actor_crop/queue_wait_normal_01.png';
const load=()=>[0,1].map(i=>decode(localStorage.getItem(SAVE_KEY+':'+i))).filter(Boolean).sort((a,b)=>b.revision-a.revision)[0]||null;
let saved=load();let state=saved||fresh(),message='';
const money=n=>new Intl.NumberFormat('vi-VN').format(n)+'đ';
function persist(){localStorage.setItem(SAVE_KEY+':'+(state.revision%2),encode(state));saved=state}
function send(type,payload){const r=action(state,type,payload);if(r.error){message=r.error}else{if(type==='REPLAY'){localStorage.removeItem(SAVE_KEY+':0');localStorage.removeItem(SAVE_KEY+':1')}state=r.state;message='';persist()}render()}
const button=(text,type,payload,extra='')=>`<button ${extra} data-type="${type}" ${payload===undefined?'':`data-payload="${String(payload)}"`}>${text}</button>`;
const card=(title,body)=>`<section class="card"><h2>${title}</h2>${body}</section>`;
function view(){
  if(state.screen==='HOME')return `<div class="hero"><h1>Xóm Nhỏ</h1><p>Chuyện Làm Ăn · Ngày 1<br>Quán nhỏ, chuyện của cả xóm.</p></div>${card('Hôm nay mở quán',`<p class="hint">Mua nguyên liệu, lắng nghe hàng xóm và tự tay ghép món cho từng người.</p>${button('Mở Quán Hôm Nay','NAVIGATE',undefined,'class="wide"')}`)}${saved&&saved.screen!=='HOME'?button('Tiếp tục ngày đang chơi','RESUME',undefined,'class="wide secondary"'):''}${button('Chơi lại từ đầu','REPLAY',undefined,'class="wide secondary"')}`;
  if(state.screen==='XOM_OI')return `${card('Xóm Ơi',`<p>Tan học, Bé Tí ghé quán. Cô Chín và Anh Tùng cũng có thể tới. Trời oi, mấy món có đá sẽ hút khách.</p><p class="hint">Chợ chỉ mở trước giờ bán. Đá và nước đường dùng chung cho hai món uống. Bé Tí có thể xin thêm chả.</p>${button('Ra chợ chuẩn bị','NAVIGATE',undefined,'class="wide"')}`)}`;
  if(state.screen==='MARKET')return `${card('Sạp chợ đầu ngõ',`<p class="hint">Chọn số phần mang về quán. Giá và số tiền trong bản thử này là dữ liệu mẫu để kiểm tra luồng.</p>${Object.entries(ingredients).map(([id,item])=>`<div class="row"><div><strong>${item.name}</strong><br><small>${money(item.price)} / phần</small></div><div class="qty">${button('−','BASKET',id+':'+Math.max(0,state.basket[id]-1),'class="secondary"')}<output>${state.basket[id]}</output>${button('+','BASKET',id+':'+(state.basket[id]+1),'class="secondary"')}</div></div>`).join('')}`)}<div class="card"><div class="row"><strong>Tổng giỏ</strong><strong>${money(total(state.basket))}</strong></div><div class="row"><span>Còn sau khi mua</span><strong>${money(state.cash-total(state.basket))}</strong></div>${button('Mang hàng về mở quán','BUY',undefined,`class="wide" ${total(state.basket)>state.cash?'disabled':''}`)}</div>`;
  if(state.screen==='SHOP'){
    const c=customers.find(x=>x.id===state.selected),left=customers.filter(x=>!state.served.includes(x.id));
    return `<div class="hero"><h2>Quán trong hẻm</h2><p>Khách đang chờ trước quầy. Chạm người bạn muốn phục vụ trước.</p></div>${card('Khách đứng chờ',left.length?left.map(x=>`<div class="card customer ${state.selected===x.id?'selected':''}">${x.id==='be_ti'?`<img class="portrait" src="${beti}" alt="Bé Tí">`:'<div class="portrait emoji">'+(x.id==='co_chin'?'👩':'👨')+'</div>'}<div class="detail"><strong>${x.name}</strong><br><small>${recipes[x.recipe].name}</small></div>${button('Chọn','SELECT',x.id)}</div>`).join(''):'<p>Mọi người đã được phục vụ.</p>')}${c?`<div class="dock"><h3>${c.name} gọi ${recipes[c.recipe].name}</h3>${c.id==='be_ti'?`<p>${c.request}</p><div class="grid">${button('Đồng ý thêm chả','EXTRA','yes')}${button('Xin dùng phần thường','EXTRA','no')}</div><p class="hint">${state.extraCha===null?'Chọn một câu trả lời.':state.extraCha?'Đã nhận thêm chả.':'Dùng công thức thường.'}</p>`:''}<hr><p class="hint">Chạm nguyên liệu để ghép món. Hàng chỉ trừ khi xác nhận đúng công thức.</p><div class="grid">${Object.entries(ingredients).map(([id,i])=>button(`${i.name} · còn ${state.stock[id]}`,'TAP',id)).join('')}</div><p>Đã chọn: ${Object.entries(state.draft).map(([id,q])=>ingredients[id].name+' ×'+q).join(', ')||'Chưa chọn'}</p><div class="grid">${button('Làm lại','CLEAR',undefined,'class="secondary"')}${button('Xác nhận món','COMMIT')}</div></div>`:''}${card('Quầy & thu chi',`<p>Tiền mặt: ${money(state.cash)} · Nợ treo: ${money(state.debt)}</p><p class="hint">Đã phục vụ ${state.served.length}/${customers.length}. Bạn có thể đóng quán và ghi nhận các đơn chưa phục vụ.</p>${button('Đóng quán','CLOSE',undefined,'class="wide secondary"')}`)}`;
  }
  return `${card('Ngày 1 khép lại',`<p>Đã phục vụ: ${state.served.length}/${customers.length} khách.</p><p>Thu bán hàng: ${money(state.revenue)} · Chi mua hàng: ${money(state.spent)} · Tiền cuối ngày: ${money(state.cash)}</p><p>${state.missed.length?'Chưa phục vụ: '+state.missed.map(id=>customers.find(c=>c.id===id).name).join(', '):'Mọi người đều nhận được món.'}</p><p class="hint">Ngày mai nghe nói có bánh mì trứng. Hôm nay chưa bán món này.</p>${button('Chơi lại Day 1','REPLAY',undefined,'class="wide"')}`)}`;
}
function render(){ $.innerHTML=`<div class="shell"><header class="top"><div><strong>XÓM NHỎ</strong><small>Ngày 1 · ${state.screen}</small></div><div>💵 ${money(state.cash)}<small>Nợ treo ${money(state.debt)}</small></div></header><div class="body">${message?`<div class="message" role="alert">${message}</div>`:''}${view()}</div><footer>Day 1 vertical slice · giá và số vốn là dữ liệu playtest · hình Bé Tí là candidate</footer></div>`}
$.addEventListener('click',e=>{const b=e.target.closest('button[data-type]');if(!b)return;const t=b.dataset.type,p=b.dataset.payload;if(t==='RESUME'){if(saved){state=saved;message='';render()}return}if(t==='REPLAY'&&!confirm('Chơi lại sẽ xóa ngày hiện tại. Tiếp tục?'))return;if(t==='BASKET'){const [id,qty]=p.split(':');send(t,{id,qty:Number(qty)})}else send(t,t==='EXTRA'?p==='yes':p)});
// An interrupted SHOP or assembly reloads directly, including the current draft.
render();
