import assert from 'node:assert/strict';
import {fresh,action,encode,decode,ingredients} from './day1-core.mjs';
let s=fresh();const apply=(t,p)=>{const r=action(s,t,p);assert.equal(r.error,undefined,`${t}: ${r.error}`);s=r.state};
apply('NAVIGATE');apply('NAVIGATE');
for(const [id,qty] of Object.entries({bread:1,cha:2,vegetable:1,ice:2,sugar_syrup:2,kumquat:1,soy_milk:1}))apply('BASKET',{id,qty});
apply('BUY');const cashAfterMarket=s.cash,initial=structuredClone(s.stock);
assert.equal(action(s,'BUY').error,'Chỉ mua hàng ở chợ.');
apply('SELECT','be_ti');apply('EXTRA',true);apply('TAP','bread');apply('TAP','cha');
assert.ok(action(s,'COMMIT').error);assert.deepEqual(s.stock,initial);
const saved=encode(s);assert.deepEqual(decode(saved),s);assert.equal(decode(saved.replace('"revision":', '"revision":999')),null);
apply('CLEAR');assert.deepEqual(s.stock,initial);
for(const id of ['bread','cha','cha','vegetable'])apply('TAP',id);
apply('COMMIT');assert.equal(s.stock.cha,0);assert.equal(s.cash,cashAfterMarket+25000);assert.equal(s.facts.be_ti.times_given_extra,1);
assert.ok(action(s,'COMMIT').error);assert.equal(s.served.length,1);
apply('SELECT','anh_tung');for(const id of ['ice','sugar_syrup','soy_milk'])apply('TAP',id);apply('COMMIT');
apply('SELECT','co_chin');for(const id of ['ice','sugar_syrup','kumquat'])apply('TAP',id);apply('COMMIT');
assert.equal(s.stock.ice,0);assert.equal(s.stock.sugar_syrup,0);assert.equal(s.served.length,3);
apply('CLOSE');assert.equal(s.screen,'DAY_RESULT');assert.equal(s.revenue,57000);assert.equal(s.cash,60000-s.spent+s.revenue);
assert.equal(Object.keys(ingredients).length,7);assert.deepEqual(s.teasedRecipeIds,['BANH_MI_TRUNG']);
console.log('Day 1: purchase exact once; invalid/cleared draft costs zero; extra cha ×2; shared drink stock; three manual services; cash reconciliation; resume checksum; close.');
