import assert from 'node:assert/strict';
import {fresh, encode, decode, calculateLedger} from './day1-core.mjs';
import {empireAction,advanceEmpire,ensureEmpire,openingEligibility,STAFF_ROLES} from './empire-engine.mjs';
import {cookingNeeds} from './shift-engine.mjs';
import {dayConfig,rosterForDay} from './day-content.mjs';
const run=(s,t,p)=>{const r=empireAction(s,t,p);assert.equal(r.error,undefined,`${t}: ${r.error}`);assert.ok(r.state.revision>=s.revision);return r.state};
function morning(day=8){let s=fresh();s.shopName='Quán Giang';s.screen='XOM_OI';s.currentDay=day;s.cash=900000;s.dayStartingCash=900000;s.rating=4;s.upgrades.vehicleCapacity=45;s.upgrades.seating=1;s.dayEvent=dayConfig(day);s.marketPrices={...s.marketPrices,...s.dayEvent.marketPrices};s.dayCustomers=rosterForDay(day,4,1,0,s.knownRecipeIds);return ensureEmpire(s)}
let locked=ensureEmpire(fresh());assert.ok(openingEligibility(locked,'school'));
let s=morning();assert.match(openingEligibility(s,'school'),/quản lý/);s=run(s,'STAFF_HIRE','manager');assert.equal(s.cash,895000);assert.equal(openingEligibility(s,'school'),null);s=run(s,'OPEN_LOCATION','school');assert.equal(s.cash,775000);assert.equal(Object.keys(s.empire.shops).length,2);assert.ok(empireAction(s,'OPEN_LOCATION','school').error);
const employee=s.empire.employees[0].id;s=run(s,'STAFF_TRAIN',employee);assert.equal(s.empire.employees[0].skill,2);assert.ok(empireAction(s,'STAFF_TRAIN',employee).error);
// Fill two physically separate inventories and confirm setup across the map.
function supply(s){s=run(s,'NAVIGATE');s=run(s,'SUGGEST_BASKET');s=run(s,'BUY');return s}
s=supply(s);s=run(s,'START_DAY');assert.ok(s.empire.mapOpen);assert.equal(s.screen,'MENU');const homeStock=structuredClone(s.stock);
s=run(s,'SWITCH_SHOP','school');assert.ok(Object.values(s.stock).every(n=>n===0));s=supply(s);const schoolStock=structuredClone(s.stock);const beforeStart=s.cash;s=run(s,'START_DAY');assert.equal(s.screen,'SHOP');assert.equal(s.cash,beforeStart-10000,'Wage once, at opening');assert.deepEqual(s.empire.shops.home.state.stock,homeStock);assert.deepEqual(s.stock,schoolStock);assert.ok(empireAction(s,'START_DAY').error);
let oldRevision=s.revision;
for(let i=0;i<300;i++){s=advanceEmpire(s,200);assert.ok(s.revision>oldRevision);oldRevision=s.revision;if(s.service?.phase==='SELECT'&&s.empire.shops.home.state.servedOrders.length)break}
assert.equal(s.servedOrders.length,0,'Owner shop stays manual');assert.ok(s.empire.shops.home.state.servedOrders.length>0,'Absent manager actually sells');assert.equal(s.clock,s.empire.shops.home.state.clock,'Shared clock');assert.ok(empireAction(s,'SWITCH_SHOP','home').error,'Cannot abandon current tickets');
const frozen=run(s,'OPEN_MAP');assert.deepEqual(advanceEmpire(frozen,5000),frozen,'Map pauses all quán');s=run(frozen,'CLOSE_MAP');const reloaded=decode(encode(s));assert.deepEqual(reloaded.empire,s.empire);s=reloaded;
for(let i=0;i<5000&&s.screen==='SHOP';i++){
 if(s.activeDecision)s=run(s,'DECIDE',{choice:'no'});
 if(s.service?.phase==='SELECT'&&s.activeCustomer?.status==='ARRIVED'){for(const[id,q]of Object.entries(cookingNeeds(s)))for(let n=s.service.selected[id]||0;n<q;n++)s=run(s,'ADD_INGREDIENT',id);s=run(s,'COOK')}
 if(s.service?.phase==='READY')s=run(s,'SERVE');s=advanceEmpire(s,200);
}
assert.equal(s.screen,'DAY_RESULT');const report=s.empire.report;assert.equal(report.shops.length,2);assert.ok(report.reconciled,JSON.stringify(report));assert.equal(report.openingCash+report.cashMovement,s.cash);for(const b of Object.values(s.empire.shops)){const ids=[...b.state.servedOrders,...b.state.missedOrders].map(x=>x.customerId);assert.equal(new Set(ids).size,ids.length);assert.equal(ids.length,b.state.dayCustomers.length);assert.ok(Object.values(b.state.stock).every(n=>n>=0))}
assert.ok(s.empire.employees[0].fatigue>0);const sharedCash=s.cash;s.revision+=100;const countdownRevision=s.revision;s=run(s,'NEXT_DAY');assert.ok(s.revision>countdownRevision,'Result countdown cannot make next-day saves look older');assert.equal(s.cash,sharedCash);assert.equal(s.currentDay,9);assert.ok(Object.values(s.empire.shops).every(b=>b.state.currentDay===9&&b.state.screen==='XOM_OI'));assert.equal(s.empire.employees[0].skill,2);
s=run(s,'STAFF_MOVE',employee+':school');assert.equal(s.empire.employees[0].shopId,'school');s=run(s,'STAFF_REST',employee);assert.ok(s.empire.employees[0].restingToday);s=run(s,'STAFF_RELEASE',employee);assert.equal(s.empire.employees.length,0);
// Role gates, persistent assignment, logistics capacity and no free inventory.
let roles=morning(15);roles=run(roles,'ENABLE_ONLINE');const stock0=structuredClone(roles.stock);for(const role of Object.keys(STAFF_ROLES))roles=run(roles,'STAFF_HIRE',role);assert.equal(roles.upgrades.vehicleCapacity,60);assert.deepEqual(roles.stock,stock0);const buyer=roles.empire.employees.find(p=>p.role==='buyer').id;roles=run(roles,'STAFF_TRAIN',buyer);assert.equal(roles.upgrades.vehicleCapacity,65,'Training logistics increases real carrying capacity');roles=run(roles,'STAFF_RELEASE',buyer);assert.equal(roles.upgrades.vehicleCapacity,45);assert.ok(empireAction(roles,'STAFF_HIRE','manager').error);
// Single-shop baseline uses the same actual hand-cooking engine.
let one=ensureEmpire(fresh());for(const[t,p]of[['SET_SHOP_NAME','Quán một'],['NAVIGATE'],['NAVIGATE'],['BUNDLE_DAY1'],['BUY'],['START_DAY']])one=run(one,t,p);
for(let i=0;i<5000&&one.screen==='SHOP';i++){if(one.activeDecision)one=run(one,'DECIDE',{choice:'yes'});if(one.service?.phase==='SELECT'){for(const[id,q]of Object.entries(cookingNeeds(one)))for(let n=0;n<q;n++)one=run(one,'ADD_INGREDIENT',id);one=run(one,'COOK')}if(one.service?.phase==='READY')one=run(one,'SERVE');one=advanceEmpire(one,200)}assert.equal(one.cash,127000);assert.equal(calculateLedger(one).grossOperatingProfit,67000);assert.ok(one.empire.report.reconciled);

function finish(s){for(let i=0;i<10000&&s.screen==='SHOP';i++){if(s.activeDecision)s=run(s,'DECIDE',{choice:'no'});if(s.service?.phase==='SELECT'&&s.activeCustomer?.status==='ARRIVED'){for(const[id,q]of Object.entries(cookingNeeds(s)))for(let n=s.service.selected[id]||0;n<q;n++)s=run(s,'ADD_INGREDIENT',id);s=run(s,'COOK')}if(s.service?.phase==='READY')s=run(s,'SERVE');s=advanceEmpire(s,200)}assert.equal(s.screen,'DAY_RESULT');assert.ok(s.empire.report.reconciled);return s}
// Third location and a planned closure: no phantom wages or free sales.
let three=morning(15);three=run(three,'STAFF_HIRE','manager');three=run(three,'OPEN_LOCATION','school');three=run(three,'SWITCH_SHOP','school');three=run(three,'STAFF_HIRE','manager');three.rating=4;three.empire.shops.school.state.rating=4;three=run(three,'OPEN_LOCATION','office');assert.equal(Object.keys(three.empire.shops).length,3);three=run(three,'TOGGLE_SHOP_DAY','home');three=run(three,'SWITCH_SHOP','school');three=supply(three);three=run(three,'START_DAY');three=run(three,'SWITCH_SHOP','office');three=supply(three);const preSalary=three.cash;three=run(three,'START_DAY');assert.equal(three.cash,preSalary-10000,'Closed home manager gets no shift wage');three=run(three,'SET_SPEED',2);three=advanceEmpire(three,200);assert.equal(three.speed,2,'Global speed survives branch projection');three=finish(three);assert.equal(three.empire.report.shops.find(x=>x.id==='home').served,0);assert.equal(three.empire.employees.find(x=>x.shopId==='home').daysWorked,0);assert.equal(three.empire.employees.find(x=>x.shopId==='school').daysWorked,1);assert.equal(three.empire.report.shops.length,3);

let delivery=morning(15);delivery=run(delivery,'ENABLE_ONLINE');delivery=run(delivery,'STAFF_HIRE','driver');delivery.dayCustomers=delivery.dayCustomers.filter(x=>x.isOnline);delivery.empire.shops.home.state.dayCustomers=structuredClone(delivery.dayCustomers);delivery=supply(delivery);delivery=run(delivery,'START_DAY');delivery=finish(delivery);assert.equal(delivery.servedOrders.length,2);assert.ok(delivery.servedOrders.every(o=>o.onlineFee===500),'Driver reduces actual collected transaction fees');assert.equal(delivery.onlineFees,1000);
// Actual portfolio progression, Days 9–15, using the shared production engine.
let campaign=ensureEmpire(fresh());for(const[t,p]of[['SET_SHOP_NAME','Quán campaign'],['NAVIGATE'],['NAVIGATE'],['BUNDLE_DAY1'],['BUY'],['START_DAY']])campaign=run(campaign,t,p);campaign=finish(campaign);
const cashChecks=[campaign.empire.report.reconciled];for(let day=2;day<=15;day++){
 campaign=run(campaign,'NEXT_DAY');if(day===2)campaign=run(campaign,'UPGRADE','bike_basket');if(day===3){campaign=run(campaign,'UPGRADE','counter');campaign=run(campaign,'LEARN_RECIPE','BANH_MI_TRUNG')}if(day===4)campaign=run(campaign,'UPGRADE','bike_basket');if(day===5)campaign=run(campaign,'UPGRADE','canopy');if(day===8){campaign=run(campaign,'STAFF_HIRE','manager');assert.equal(openingEligibility(campaign,'school'),null);campaign=run(campaign,'OPEN_LOCATION','school')}
 for(const id of Object.keys(campaign.empire.shops)){campaign=run(campaign,'SWITCH_SHOP',id);campaign=supply(campaign);campaign=run(campaign,'START_DAY');if(campaign.screen==='SHOP')break;}
 campaign=finish(campaign);cashChecks.push(campaign.empire.report.reconciled);campaign=decode(encode(campaign));assert.equal(campaign.currentDay,day);
}
console.log(JSON.stringify({status:'PASS',twoShopDay:report,roles:Object.keys(STAFF_ROLES),singleCash:one.cash,sharedClock:true,backgroundRealSales:true,reload:true,thirdLocation:true,plannedClosure:true,campaignDays:15,portfolioDays:8,allDailyCashReconciled:cashChecks.every(Boolean)},null,2));
