import assert from 'node:assert/strict';
const data = new Map();
const app = { innerHTML: '', dataset: {}, addEventListener() {} };
globalThis.document = { querySelector(selector) { return selector === '#app' ? app : null; } };
globalThis.localStorage = { getItem(k) { return data.get(k) ?? null; }, setItem(k, v) { data.set(k, v); }, removeItem(k) { data.delete(k); } };
globalThis.window = { confirm: () => true };
await import('./main.mjs');
const { send, getState } = window.__xomNho;
assert.match(app.innerHTML, /shop-name-input/);
send('SET_SHOP_NAME', 'Quán Hẻm Nhỏ');
send('NAVIGATE');
assert.match(app.innerHTML, /Quán Hẻm Nhỏ/);
send('NAVIGATE');
send('BUNDLE_DAY1');
send('BUY');
assert.match(app.innerHTML, /3 chỗ trên quầy/);
send('START_DAY');
assert.match(app.innerHTML, /Ngày 1/);
send('CLOSE');
assert.match(app.innerHTML, /Tự sang ngày sau/);
assert.match(app.innerHTML, /Khách nói gì/);
send('NEXT_DAY');
assert.match(app.innerHTML, /tắc 3.000đ/);
send('UPGRADE', 'counter');
assert.equal(getState().upgrades.counterSlots, 3, 'Cannot buy upgrade without cash');
send('NAVIGATE');
assert.match(app.innerHTML, /3\.000đ \/ trái/);
send('BUY');
assert.match(app.innerHTML, /Bánh mì ốp la/);
assert.match(app.innerHTML, /Điều kiện mở: Nâng cấp quầy và học công thức từ Ngày 3/);
assert.ok(!getState().knownRecipeIds.includes('BANH_MI_TRUNG'));
assert.match(app.innerHTML, /data-recipe="BANH_MI_TRUNG"[^>]*disabled/);
console.log('UI smoke: onboarding name, day transition, market inflation, unaffordable upgrade and locked menu PASS');
window.__xomNho.clearAllTimers();
