// Two-shop UI fixture, real browser actions, fake time; no video.
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
(async()=>{
 const root=process.cwd(),server=http.createServer((req,res)=>{const url=decodeURIComponent(req.url.split('?')[0]);let file=path.resolve(root,'.'+url);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}if(url.endsWith('/'))file+='/index.html';fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return}res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg'}[path.extname(file)]||'application/octet-stream'));res.end(data)})});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const b=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await b.newPage({viewport:{width:390,height:700}}),errors=[],failures=[];p.on('pageerror',x=>errors.push(x.message));p.on('response',r=>{if(r.status()>=400)failures.push(r.url())});await p.clock.install();await p.clock.pauseAt(new Date(await p.evaluate(()=>Date.now())));await p.goto(`http://127.0.0.1:${server.address().port}/game/`);
 await p.evaluate(async()=>{const{fresh,encode,SAVE_KEY}=await import('./day1-core.mjs');const{ensureEmpire}=await import('./empire-engine.mjs');const{dayConfig,rosterForDay}=await import('./day-content.mjs');let s=fresh();s.shopName='Quán Giang';s.screen='XOM_OI';s.currentDay=8;s.rating=4;s.cash=900000;s.dayStartingCash=900000;s.revision=10000;s.upgrades.vehicleCapacity=45;s.upgrades.seating=1;s.dayEvent=dayConfig(8);s.marketPrices={...s.marketPrices,...s.dayEvent.marketPrices};s.dayCustomers=rosterForDay(8,4,1,0,s.knownRecipeIds);s=ensureEmpire(s);localStorage.removeItem(SAVE_KEY+':0');localStorage.removeItem(SAVE_KEY+':1');localStorage.setItem(SAVE_KEY+':0',encode(s))});await p.reload();
 const get=()=>p.evaluate(()=>window.__xomNho.getState());
 await p.locator('[data-type=OPEN_STAFF]').click();await p.locator('[data-type=STAFF_HIRE][data-payload=manager]').click();assert.equal((await get()).empire.employees.length,1);await p.locator('[data-type=STAFF_TRAIN]').click();assert.equal((await get()).empire.employees[0].skill,2);fs.mkdirSync('docs/empire_evidence',{recursive:true});await p.screenshot({path:'docs/empire_evidence/staff.png',animations:'disabled'});await p.locator('[data-type=CLOSE_STAFF]').click();
 await p.locator('[data-type=OPEN_MAP]').click();await p.locator('[data-type=MAP_FOCUS][data-payload=school]').click();await p.locator('[data-type=OPEN_LOCATION][data-payload=school]').click();assert.equal(Object.keys((await get()).empire.shops).length,2);
 for(const [width,height]of[[360,640],[390,700],[430,932]]){await p.setViewportSize({width,height});const metrics=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,small:[...document.querySelectorAll('.empire-panel button')].filter(x=>{const r=x.getBoundingClientRect();return r.width<44||r.height<44}).map(x=>x.textContent)}));assert.equal(metrics.overflow,false);assert.deepEqual(metrics.small,[])}await p.setViewportSize({width:390,height:700});await p.screenshot({path:'docs/empire_evidence/map.png',animations:'disabled'});await p.locator('[data-type=CLOSE_MAP]').click();
 async function supply(){await p.locator('[data-type=NAVIGATE]').click();await p.locator('[data-type=SUGGEST_BASKET]').click();await p.locator('[data-type=BUY]').click();await p.locator('[data-type=START_DAY]').click()}
 await supply();assert.ok((await get()).empire.mapOpen);await p.locator('[data-type=MAP_FOCUS][data-payload=school]').click();await p.locator('[data-type=SWITCH_SHOP][data-payload=school]').click();await supply();assert.equal((await get()).screen,'SHOP');const payrollCash=(await get()).cash;await p.clock.runFor(5500);assert.equal((await get()).servedOrders.length,0);assert.ok((await get()).empire.shops.home.state.servedOrders.length>0);assert.ok((await get()).cash>payrollCash);
 const preReload=await get();await p.reload();const restored=await get();assert.equal(restored.empire.activeShopId,'school');assert.equal(restored.cash,preReload.cash);assert.deepEqual(restored.empire.shops.home.state.servedOrders,preReload.empire.shops.home.state.servedOrders);
 await p.locator('.play-options summary').click();await p.clock.runFor(600);assert.equal(await p.locator('#play-options').getAttribute('open'),'');await p.locator('[data-type=OPEN_MAP]').click();const clock=(await get()).clock;await p.clock.runFor(5000);assert.equal((await get()).clock,clock);await p.locator('[data-type=MAP_FOCUS][data-payload=home]').click();await p.locator('[data-type=SWITCH_SHOP][data-payload=home]').click();assert.equal((await get()).empire.activeShopId,'school');assert.ok(await p.locator('.empire-panel .alert-message').isVisible());await p.screenshot({path:'docs/empire_evidence/live_map.png',animations:'disabled'});await p.locator('[data-type=CLOSE_MAP]').click();await p.locator('.play-options summary').click();
 for(let i=0;i<3000&&(await get()).screen==='SHOP';i++){let s=await get();if(s.activeDecision){await p.locator('[data-type=DECIDE][data-payload=no]').click();s=await get()}if(s.service?.phase==='SELECT'&&s.activeCustomer?.status==='ARRIVED'){const needs=await p.evaluate(async()=>{const{cookingNeeds}=await import('./shift-engine.mjs');return cookingNeeds(window.__xomNho.getState())});for(const[id,q]of Object.entries(needs))for(let n=s.service.selected[id]||0;n<q;n++)await p.locator(`[data-type=ADD_INGREDIENT][data-payload=${id}]`).click();await p.locator('[data-type=COOK]').click()}if((await get()).service?.phase==='READY')await p.locator('[data-type=SERVE]').click();await p.clock.runFor(200)}
 const result=await get();assert.equal(result.screen,'DAY_RESULT');assert.ok(result.empire.report.reconciled);assert.equal(result.empire.report.shops.length,2);await p.screenshot({path:'docs/empire_evidence/result.png',fullPage:true,animations:'disabled'});await p.locator('#day-ledger-details summary').click();const remain=(await get()).resultRemainingMs;await p.clock.runFor(15000);assert.equal((await get()).resultRemainingMs,remain);await p.locator('[data-type=NEXT_DAY]').click();assert.equal((await get()).currentDay,9);assert.ok(Object.values((await get()).empire.shops).every(x=>x.state.currentDay===9));
 await p.locator('[data-type=OPEN_STAFF]').click();await p.locator('[data-type=STAFF_HIRE][data-payload=manager]').click();await p.locator('[data-type=CLOSE_STAFF]').click();await supply();await p.locator('[data-type=MAP_FOCUS][data-payload=home]').click();await p.locator('[data-type=SWITCH_SHOP][data-payload=home]').click();await supply();await p.locator('.play-options summary').click();await p.clock.runFor(600);assert.equal(await p.locator('#play-options').getAttribute('open'),'');await p.locator('[data-type=OPEN_MAP]').click();const rev=(await get()).revision,breakClock=(await get()).clock;await p.locator('[data-type=MAP_FOCUS][data-payload=school]').click();await p.locator('[data-type=SWITCH_SHOP][data-payload=school]').click();assert.equal((await get()).empire.activeShopId,'school');assert.ok((await get()).revision>rev);assert.equal((await get()).clock,breakClock);await p.reload();assert.equal((await get()).empire.activeShopId,'school');
 assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);const report={status:'PASS',fixtureStart:{day:8,cash:900000,rating:4},shops:result.empire.report.shops.map(x=>({id:x.id,served:x.served,profit:x.profit})),reconciled:result.empire.report.reconciled,closingCash:result.cash,hireTrain:true,backgroundSales:true,manualOwner:true,mapPause:true,midOrderSwitchBlocked:true,breakSwitch:true,realReload:true,nextDaySynchronized:true,errors,failures,videoRecorded:false};fs.writeFileSync('docs/empire_evidence/browser_smoke.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));await b.close();await new Promise(r=>server.close(r));
})().catch(e=>{console.error(e);process.exit(1)});
