// Targeted browser smoke. Uses the real UI and fake time, never records video.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
 const b=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? {executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']} : {})});
 const http=require('node:http'), path=require('node:path');
 const root=process.cwd();
 const server=http.createServer((req,res)=>{ const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0])); if(!file.startsWith(root+path.sep)) {res.writeHead(403).end();return;} const target=req.url.split('?')[0].endsWith('/')?file+'/index.html':file; fs.readFile(target,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'}[path.extname(target)]||'application/octet-stream'));res.end(data);});});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const errors=[],failures=[];
 const p=await b.newPage({viewport:{width:390,height:844}});
 p.on('pageerror',e=>errors.push(e.message));
 p.on('response',r=>{if(r.status()>=400) failures.push(`${r.status()} ${r.url()}`)});
 await p.clock.install();
 await p.goto(process.env.XOM_GAME_URL || `http://127.0.0.1:${server.address().port}/game/`);
 await p.locator('#shop-name-input').fill('Quán Bé Mây Ở Đầu Hẻm');
 await p.locator('[data-type=SET_SHOP_NAME]').click();
 await p.locator('[data-type=NAVIGATE]').click();
 await p.locator('[data-type=BUNDLE_DAY1]').click();
 await p.locator('[data-type=BUY]').click();
 await p.locator('[data-type=START_DAY]').click();
 await p.clock.runFor(5200);
 assert.equal(await p.evaluate(()=>window.__xomNho.getState().service?.phase),'PREP');
 await p.reload();
 assert.equal(await p.evaluate(()=>window.__xomNho.getState().service?.phase),'PREP');
 await p.clock.runFor(16000);
 assert.equal(await p.evaluate(()=>window.__xomNho.getState().activeDecision?.id),'EXTRA_CHA');
 const frozen=await p.evaluate(()=>window.__xomNho.getState().clock);
 await p.clock.runFor(3000);
 assert.equal(await p.evaluate(()=>window.__xomNho.getState().clock),frozen);
 await p.locator('[data-type=DECIDE][data-payload=yes]').click();
 await p.clock.runFor(1200);
 assert.equal(await p.evaluate(()=>window.__xomNho.getState().waitingQueue.length),2);
 await p.locator('[data-type=PRIORITIZE][data-payload=anh_tung]').last().click();
 assert.equal(await p.evaluate(()=>window.__xomNho.getState().prioritizedCustomerId),'anh_tung');
 await p.locator('[data-type=FOCUS_BOOST]').click();
 await p.locator('[data-type=TOGGLE_PAUSE]').click();
 const before=await p.evaluate(()=>({clock:window.__xomNho.getState().clock,boost:window.__xomNho.getState().focusBoost.remainingSeconds}));
 await p.clock.runFor(4000);
 assert.deepEqual(await p.evaluate(()=>({clock:window.__xomNho.getState().clock,boost:window.__xomNho.getState().focusBoost.remainingSeconds})),before);
 await p.locator('[data-type=TOGGLE_PAUSE]').click();
 const viewports=[];
 for(const width of [360,390,430]) {
  await p.setViewportSize({width,height:844});
  const metrics=await p.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,broken:[...document.images].filter(i=>i.complete&&i.naturalWidth===0).map(i=>i.src),smallButtons:[...document.querySelectorAll('button:not(:disabled)')].filter(e=>{const r=e.getBoundingClientRect();return r.width<43.9||r.height<43.9}).map(e=>e.textContent.trim())}));
  assert.ok(metrics.scrollWidth<=width,`Overflow at ${width}`);
  assert.deepEqual(metrics.broken,[]);
  assert.deepEqual(metrics.smallButtons,[]);
  viewports.push(width);
 }
 await p.setViewportSize({width:390,height:844});
 fs.mkdirSync('docs/playable_evidence',{recursive:true});
 await p.screenshot({path:'docs/playable_evidence/shop.png',fullPage:true});
 await p.clock.runFor(41000);
 assert.equal(await p.evaluate(()=>window.__xomNho.getState().screen),'DAY_RESULT');
 const result=await p.evaluate(()=>({cash:window.__xomNho.getState().cash,served:window.__xomNho.getState().servedOrders.length,missed:window.__xomNho.getState().missedOrders.length}));
 assert.deepEqual(result,{cash:127000,served:6,missed:2});
 await p.locator('#day-ledger-details summary').click();
 const left=await p.evaluate(()=>window.__xomNho.getState().resultRemainingMs);
 await p.clock.runFor(15000);
 assert.equal(await p.evaluate(()=>window.__xomNho.getState().resultRemainingMs),left);
 await p.reload();
 assert.equal(await p.locator('#day-ledger-details').getAttribute('open'),'');
 await p.screenshot({path:'docs/playable_evidence/result.png',fullPage:true});
 await p.locator('#day-ledger-details summary').click();
 await p.clock.runFor(left+1000);
 assert.equal(await p.evaluate(()=>window.__xomNho.getState().currentDay),2);
 await p.locator('[data-type=NAVIGATE]').click();
 await p.locator('[data-type=SUGGEST_BASKET]').click();
 assert.ok(await p.evaluate(()=>Object.values(window.__xomNho.getState().basket).reduce((n,q)=>n+q,0)>0));
 assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);
 const report={status:'PASS',uiDay1:result,viewports,errors,failures,realReload:true,priority:true,boost:true,pause:true,resultCountdownPreserved:true,suggestBasket:true,videoRecorded:false};
 fs.writeFileSync('docs/playable_evidence/browser_smoke.json',JSON.stringify(report,null,2)+'\n');
 console.log(JSON.stringify(report,null,2));
 await b.close();
 await new Promise(resolve=>server.close(resolve));
})().catch(e=>{console.error(e);process.exit(1)});
